### ISSUE TITLE
更新jwt tag  affected/package: go-filter/jwt

### ISSUE THREAD

**Issue by Ltd5552** [trpc-ecosystem/go-filter#13]
您好，这边发现当前jwt的tag落后7次提交，导致最新代码中对mod版本的修改无法使用，v1.0.0版本存在问题是gomod版本仍旧为1.14，导致使用时因版本过低异常，希望解决下，谢谢！
![image](https://github.com/trpc-ecosystem/go-filter/assets/77269387/1098a643-7ff4-4369-b0a7-44b8dd1a1da8)
![image](https://github.com/trpc-ecosystem/go-filter/assets/77269387/8b600084-6ea9-4b03-8a6a-99510ad402dc)

### What version of trpc-go-filter are you using?
trpc-filter/jwt v1.0.0

### Does this issue reproduce with the latest release?
yes 1.0.0

### What operating system and processor architecture are you using (`go env`)?
1.20

### What did you expect to see?
更新jwt的tag，修改旧tag导致的go版本过旧问题

### What did you see instead?

**Comment by WineChord** [comment]
https://github.com/trpc-ecosystem/go-filter/releases/tag/jwt%2Fv1.0.1

**Comment by Ltd5552** [comment]
> https://github.com/trpc-ecosystem/go-filter/releases/tag/jwt%2Fv1.0.1

感谢！
